version: "3.9"
services:
  mongo_for_express:
    image: "bitnami/mongodb:latest"
    restart: unless-stopped
    ports:
      - "27020:27017"
    volumes:
      - ./mongo_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_DATABASE=ums
  redis_for_express:
    image: "bitnami/redis:latest"
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - "./redis_data:/bitnami/redis/data"
    environment:
      - REDIS_PASSWORD=admin
      - REDIS_IO_THREADS=4
      - REDIS_IO_THREADS_DO_READS=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
